### ISSUE TITLE
change OWNCLOUD_INSTALL_DIR fails

### ISSUE THREAD

**Issue by martingabelmann** [sameersbn/docker-owncloud#1]
had to change this env-var because i already run a apache-container with `/var/www/public/`. 

seems to fail [there](https://github.com/sameersbn/docker-owncloud/blob/master/runtime/functions#L91), a `sudo -HEu ${OWNCLOUD_USER} mkdir -p ${OWNCLOUD_INSTALL_DIR}` at [L86](https://github.com/sameersbn/docker-owncloud/blob/master/runtime/functions#L86) may fix it.

thanks :+1:

**Comment by sameersbn** [comment]
@martingabelmann I don't think I completely understand the issue.

**Comment by martingabelmann** [comment]
```
docker run -d --name=owncloud \
--env 'OWNCLOUD_FQDN=owncloud' \
--env 'OWNCLOUD_INSTALL_DIR=/var/www/public/owncloud' \
--link postgresql:postgresql \
--volume /home/www/ocdata/:/var/lib/owncloud/ \
--volume /home/www/htdocs/owncloud/:/var/www/public/owncloud/ \
sameersbn/owncloud:latest
```

then the container stops and `docker logs owncloud` says 

```
cp: cannot create regular file '/var/www/public/owncloud/config/autoconfig.php': No such file or directory
```

**Comment by martingabelmann** [comment]
Okay I tested some things and had a `aha-moment`!

The installation-stuff in `install.sh` is done during the build with the default value for `OWNCLOUD_INSTALL_DIR`. At this point everyithing is  inside the image, so if the path is changed in the container, the webfiles arent reachable lost.

My workaround was to move th whole content of `install.sh` into the `entrypoint.sh` (on top of it) so that the things are done in the container... Now it worked for me if I run my apache-container with `--volumes-from owncloud`.

But now I understand why this issue is sensless (and therefore the workaround), because the original setup was about to store the webfiles inside the conainer only and to share them with the apache-container. So in my case the storage-container has become reduntant after the first run, (it would alos work if i stop the owncloud-container because the files are availabel from the host)...

So i seems, that I have to manage this like the howto and introduce vhosts in my apache-setup...

greetings
Martin
